### ISSUE TITLE
Game doesnt even create a world

### ISSUE THREAD

**Issue by 12MBTT** [Saikel-Orado/Spontaneous-Replace#1]
I have around 400 mods in my modpack but I know what im doin. But with this mod, the game crashed whenever i create a new world.I checked latest log and i found your mod is causing crash

 Here's latest

[latest.log](https://github.com/Saikel-Orado/Spontaneous-Replace/files/11260369/latest.log)

**Comment by Saikel-Orado-Liu** [comment]
OK, I will check the log
Have you tried installing only this mod? This may be the reason for the Mod conflict

**Comment by Saikel-Orado-Liu** [comment]
> 

I now know the source of the problem, please be patient as I have not encountered this issue in any of my development projects
Thank you for submitting

**Comment by Saikel-Orado-Liu** [comment]
> I have around 400 mods in my modpack but I know what im doin. But with this mod, the game crashed whenever i create a new world.I checked latest log and i found your mod is causing crash
> 
> Here's latest
> 
> [latest.log](https://github.com/Saikel-Orado/Spontaneous-Replace/files/11260369/latest.log)

After my investigation, I found out that this was caused by mod conflicts, but it was not caused by mods such as sodium and Iris, but rather by DisableCustomWorldsAdvice. I suspect it is because my mod also has code blocks with the same functionality

**Comment by Saikel-Orado-Liu** [comment]
You only need to delete DisableCustomWorldsAdvice to solve this problem
