### ISSUE TITLE
Rendering Mob Crash

### ISSUE THREAD

**Issue by 12MBTT** [Saikel-Orado/Spontaneous-Replace#2]
Hi, its me again :D
I've come with another issue. When I spawn spontaneus's mobs and wait for a while, the game crashes

[crash-2023-05-27_18.15.31-client.txt](https://github.com/Saikel-Orado/Spontaneous-Replace/files/11601323/crash-2023-05-27_18.15.31-client.txt)

Crash report says theres a rendering issue so I hope you can fix it :)
Have a good day

**Comment by Saikel-Orado-Liu** [comment]
> 

emmm, I will try. But you can try installing only this Mod, I'm worried it may be a compatibility issue

**Comment by 12MBTT** [comment]
I think sodium or indium etc. are incompatible with rendering this mob

**Comment by Saikel-Orado-Liu** [comment]
> Author

no no, I tested. These optimized Mods are compatible, as you have too many Mods here, I am not sure which Mod caused it. There are also many similar errors on the internet, most of which are due to Mod incompatibility or modifying player skins, etc

**Comment by 12MBTT** [comment]
I'm sorry for your effort but your mod's textures are so nice looking, the animations are good I dont want to uninstall this mod

**Comment by Saikel-Orado-Liu** [comment]
> I'm sorry for your effort but your mod's textures are so nice looking, the animations are good I dont want to uninstall this mod

its ok. If possible, I will try my best to solve it. Thank you for your support
