### ISSUE TITLE
can't enchant alloy equipments by enchantment book

### ISSUE THREAD

**Issue by Aike2071** [Saikel-Orado/Spontaneous-Replace#4]
my game version is 1.20.6,and using other enchantment mods(dark enchanting) is also unable to enchant alloy equipments.It's disappointing that such powerful equipments can only be enchanted randomly :(

**Comment by Saikel-Orado-Liu** [comment]
copy that. It will be fixed in the next version.

**Comment by Aike2071** [comment]
thanks for noticing that
